---
name: Danger Report
on:
  pull_request:
    types:
      [
        assigned,
        edited,
        labeled,
        opened,
        ready_for_review,
        reopened,
        review_requested,
        synchronize,
        unassigned,
        unlabeled,
      ]

jobs:
  danger-check:
    uses: ./.github/workflows/danger-check.yaml
    with:
      dangerfile-path: ./danger/danger.ts
    secrets:
      danger-api-token: ${{ secrets.GITHUB_TOKEN }}
