name: Danger

on:
  workflow_call:
    inputs:
      dangerfile-path:
        description: "danger file to execute. e.g. danger/dangerfile-pull-request-validations.ts"
        required: true
        type: string

      fetch-depth:
        description: "depth of repository to fetch out"
        required: false
        default: 1
        type: string

    secrets:
      danger-api-token:
        description: "api token used by danger, if danger check uses elevated API then default GITHUB_TOKEN will not suffice"
        required: true

jobs:
  danger-check:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          client-id: ${{ secrets.CIMON_CLIENT_ID }}
          secret: ${{ secrets.CIMON_CLIENT_SECRET }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: 'danger/yarn.lock'

      - name: install dependencies
        working-directory: ./danger
        run: |
          yarn install --frozen-lockfile

      - name: Rerun danger check on pull request
        working-directory: ./danger
        run: |
          yarn danger ci --dangerfile ./danger.ts
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.danger-api-token }}
