name: Danger

on:
  workflow_call:
    inputs:
      dangerfile-path:
        description: "danger file to execute. e.g. danger/dangerfile-pull-request-validations.ts"
        required: true
        type: string

      fetch-depth:
        description: "depth of repository to fetch out"
        required: false
        default: 1
        type: string

    secrets:
      danger-api-token:
        description: "api token used by danger, if danger check uses elevated API then default GITHUB_TOKEN will not suffice"
        required: true

concurrency:
  group: danger-${{ github.ref }}
  cancel-in-progress: true

jobs:
  danger-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: cache danger
        id: cache-danger
        uses: actions/cache@v4
        env:
          cache-name: cache-danger
        with:
          path: /opt/hostedtoolcache/node/18**/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-danger-12.3.3

      - name: install yarn dependencies
        if: steps.cache-danger.outputs.cache-hit != 'true'
        run: |
          npm install -g danger@12.3.3 typescript@5.6.3
          npm list -g
          ls /opt/hostedtoolcache/node/18**/

      - name: Rerun danger check on pull request
        run: |
          danger ci --dangerfile ${{ inputs.dangerfile-path }}
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.danger-api-token }}
