name: Label Deployment Tasks

on:
  pull_request:
  push:

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR With Deployment Task
        uses: actions/github-script@v6
        with:
          script: |
            const LABEL = "Deployment Task";
            const MIGRATION_PREFIX_PATH = "lib/identity/repo/data_migrations/";
            const BASE_PARAMS = { owner: context.repo.owner, repo: context.repo.repo };

            const findMigrationFile = (files) => {
                return files.find((file) => ["modified", "added"].includes(file.status) && file.filename.startsWith(MIGRATION_PREFIX_PATH));
            };
            const findMigrationFileForPr = async (pr) => {
                const iterator = github.paginate.iterator(github.rest.pulls.listFiles, { ...BASE_PARAMS, pull_number: pr.number })

                for await (const { data: files } of iterator) {
                    migrationFile = findMigrationFile(files)
                    if (migrationFile) return {...pr, migrationFile: migrationFile}
                }
                return pr
            }
            const getPrsWithMaybeMigrationFile = async (sha) => {
                const {data: pullRequests} = await github.rest.repos.listPullRequestsAssociatedWithCommit({ ...BASE_PARAMS, commit_sha: sha })
                return Promise.all(pullRequests.map((pr) => findMigrationFileForPr(pr)))
            };

            const pullRequests = await getPrsWithMaybeMigrationFile(process.env.GITHUB_SHA);
            const labelPromises = await pullRequests.forEach(async (pr) => {
                if (pr.migrationFile) {
                    console.log(`Applying ${LABEL} label to PR:${pr.number} because of file ${pr.migrationFile.filename}`);
                    await github.rest.issues.addLabels({ ...BASE_PARAMS, issue_number: pr.number, labels: [LABEL] });
                } else if (pr.labels.includes(LABEL)) {
                    console.log(`Removing ${LABEL} label from PR:${pr.number}`);
                    await github.rest.issues.removeLabel({ ...BASE_PARAMS, issue_number: pr.number, name: LABEL });
                }
            });
