name: PR_review

on:
  pull_request_review:
    types: [submitted, edited]
  pull_request:

#
jobs:
  test:
    if: ${{ !github.event.pull_request.draft && (startsWith(github.event.pull_request.base.ref, 'release/') || github.event.pull_request.base.ref == 'develop') }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}
          echo ${{ github.event.pull_request.draft }}
